#define mini_buf 4096
#define mini_vsnprintf generate
#define mini_itodec generate
#define mini_printl generate
#define mini_dtodec generate
#define mini_snprintf generate
#define mini_memfrob generate
#define mini__itobin generate
#define mini_def generate
#define mini_dprintf generate
#define mini_print generate
#define mini_uitodec generate
#define mini_ioctl generate
#define mini_getcwd generate
#define mini_stat generate
#define mini_gettimeofday generate
#define mini_dup3 generate
#define mini_mprotect generate
#define mini_fstat generate
#define mini_creat generate
#define mini_time generate
#define mini_select generate
#define mini_getpid generate
#define mini_rename generate
#define mini_dup generate
#define mini_fsync generate
#define mini_unlink generate
#define mini_tcsetattr generate
#define mini_dup2 generate
#define mini_lseek generate
#define mini_open generate
#define mini_def generate
#define mini_read generate
#define mini_tcgetattr generate
#define mini_ftruncate generate
#define mini_close generate
#define mini_write generate
#define mini_itohex generate
#define mini_fread generate
#define mini_putchar generate
#define mini_fwrite generate
#define mini_feof generate
#define mini_fputs generate
#define mini_fprintf generate
#define mini_fgetpos generate
#define mini_fopen generate
#define mini_rewind generate
#define mini__itohex generate
#define mini_sprintf generate
#define mini_puts generate
#define mini_ftell generate
#define mini_itoHEX generate
#define mini_fseek generate
#define mini_fsetpos generate
#define mini_fputc generate
#define mini_printf generate
#define mini_fclose generate
#define mini_fileno generate
#define mini_getenv generate
#define mini_rand generate
#define mini_atoi generate
#define mini_srand generate
#define mini_free generate
#define mini_malloc generate
#define mini_strcat generate
#define mini_memcpy generate
#define mini_strncpy generate
#define mini_strcmp generate
#define mini_strerror generate
#define mini_strlen generate
#define mini_memcmp generate
#define mini_strncmp generate
#define mini_memset generate
#define mini_strcpy generate
#define mini_isprint generate
#define mini_isspace generate
